actor_codes = {
'AGR': 'Agriculture: individuals and groups involved in the practices of crop cultivation including government agencies whose primary concern is agricultural issues',
'BUS': 'Business: businessmen, companies, and enterprises, not including MNCs',
'COP': 'Police forces, officers, criminal investigative units, protective agencies',
'CRM': 'Criminal: corresponding to individuals involved in or allegedly involved in the deliberate breaking of state or international laws primarily for profit',
'CVL': 'Civilian individuals or groups sometimes used as catch-all for individuals or groups for whom no other role category is appropriate',
'DEV': 'Development: individuals or groups concerned primarily with development issues of varying types including infrastructure creation, democratization et al.',
'EDU': 'Education: educators, schools, students, or organizations dealing with education',
'ELI': 'Elites: former government officials, celebrities, spokespersons for organizations without further role categorization (George Soros, former Secretary of Defense, Bono)',
'ENV': 'Environmental: entities for whom environmental and ecological issues are their primary focus, includes wildlife preservation, climate change, etc.',
'GOV': 'Government: the executive, governing parties, coalitions partners, executive divisions',
'HLH': 'Health: individuals, groups and organizations dealing with health and social welfare practices (doctors, Doctors Without Borders)',
'HRI': 'Human Rights: actors for whom their primary area of operation or expertise is with documenting and/or correcting human rights concerns',
'IGO': 'Inter-governmental organizations',
'IMG': 'International Militarized Groups',
'INS': 'Insurgents (rebels): all rebels who attempt to overthrow their national government',
'INT': 'International or transnational actors who cannot be further specified as IGO, UIS, NGO, NGM, or MNC',
'JUD': 'Judiciary: judges, courts',
'LAB': 'Labor: specifically individuals in or elements of organized labor, organizations concerned with labor issues',
'LEG': 'Legislature: parliaments, assemblies, lawmakers, references to specific legislative entities or sub-entities such as committees',
'MED': 'Media: journalists, newspapers, television stations also includes providers of internet services and other forms of mass information dissemination',
'MIL': 'Military: troops, soldiers, all state-military personnel/equipment',
'MNC': 'Multi-national corporation',
'MOD': 'Moderate: “moderate,” “mainstream,” etc.',
'NGM': 'Non-governmental movements',
'NGO': 'Non-governmental organizations',
'OPP': 'Political opposition: opposition parties, individuals, anti-government activists',
'RAD': 'Radical: “radical,” “extremist,” “fundamentalist,” et',
'REB': 'Rebels: armed and violent opposition groups, individuals',
'REF': 'Refugees: also refers to agencies or MNCs dealing with population migration and relocation issues',
'SEP': 'Separatist rebels: all rebels who try to emancipate their region from its country',
'SPY': 'State intelligence services and members including covert operations groups as well as intelligence collection and analyses',
'UAF': 'Armed forces aligned neither with nor against their government',
'UIS': 'Unidentified state actors',
}